/**
 * Email templates for outreach drip sequences — shared between prospect-replenish and drip-sender
 */

const TEMPLATES = {
  'ABLE-AMMO': { subjects: ['Quick idea for {{SITE_NAME}}','Re: Quick idea for {{SITE_NAME}}','Re: Quick idea for {{SITE_NAME}}','Re: Quick idea for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nI came across your piece on {{ARTICLE_TITLE}} — solid breakdown. I'm working with Able Ammo and we've been putting together content around ammunition selection, range safety, and hunting season prep that I think would fit well on your site.\n\nWould you be open to us contributing an article? We'd handle all the writing.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just floating this back up. We have a few article ideas ready to go — happy to send topics over if that's easier.\n\nYam`,`Hi {{FIRSTNAME}}, wanted to check in one more time. We're flexible on topics and can match your editorial style. We're also happy to cover any editorial fees on your end. Let me know if there's interest.\n\nYam`,`Last one from me — if the timing isn't right, no worries at all. If content collaborations are something you do down the road, feel free to reach out.\n\nYam`] },
  'DR-DABBER': { subjects: ['Content collab with {{SITE_NAME}}?','Re: Content collab with {{SITE_NAME}}?','Re: Content collab with {{SITE_NAME}}?','Re: Content collab with {{SITE_NAME}}?'], bodies: [`Hi {{FIRSTNAME}},\n\nBeen following your content — your {{ARTICLE_TITLE}} was a great read. I work with Dr. Dabber (premium vaporizer brand) and we've got some article ideas around vaporizer tech, concentrate guides, and device comparisons that could work well for your audience.\n\nWould you be open to a contributed piece? We handle the writing.\n\nCheers,\nYam`,`Hey {{FIRSTNAME}}, just circling back. Happy to send over a few topic ideas tailored to your site if that helps.\n\nYam`,`Hi {{FIRSTNAME}}, checking in one last time on this. We can adapt to your guidelines and are glad to cover any editorial or publishing fees. Let me know if there's an opening.\n\nYam`,`Closing the loop — totally understand if it's not the right fit. Door's always open if you're looking for cannabis/vape content contributors down the road.\n\nYam`] },
  'FELINA': { subjects: ['Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nLove what you're doing with {{SITE_NAME}} — your post on {{ARTICLE_TITLE}} really resonated. I'm working with Felina (women's intimates & loungewear brand) and we'd love to contribute an article on topics like finding the perfect bra fit, loungewear essentials, or body-positive fashion.\n\nWould you be interested in a contributed piece? We write it, you publish it.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just bumping this up. We have a few topics ready — happy to share them so you can pick what fits.\n\nYam`,`Hi {{FIRSTNAME}}, one more nudge. We write to your style guidelines and are happy to cover any editorial fees involved. Would love to make this work.\n\nYam`,`Last message from me — if the timing isn't right, no hard feelings. Happy to reconnect whenever it makes sense.\n\nYam`] },
  'MILL-PACKAGING': { subjects: ['Guest post for {{SITE_NAME}}?','Re: Guest post for {{SITE_NAME}}?','Re: Guest post for {{SITE_NAME}}?','Re: Guest post for {{SITE_NAME}}?'], bodies: [`Hi {{FIRSTNAME}},\n\nFound your site while researching packaging content — really liked your take on {{ARTICLE_TITLE}}. I work with Mill Packaging and we've put together some articles on custom packaging strategy, sustainable packaging options, and how unboxing impacts brand loyalty.\n\nOpen to us contributing a piece? We handle all the writing.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just following up. Can send topic options your way if that's helpful — no pressure.\n\nYam`,`Hi {{FIRSTNAME}}, circling back here. We're flexible on angle and happy to cover any editorial costs on your side. Let me know if there's interest.\n\nYam`,`Closing the loop on this one. If guest content is something you consider in the future, feel free to reach out anytime.\n\nYam`] },
  'PRIMERX': { subjects: ['Article contribution for {{SITE_NAME}}','Re: Article contribution for {{SITE_NAME}}','Re: Article contribution for {{SITE_NAME}}','Re: Article contribution for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nYour article on {{ARTICLE_TITLE}} was a useful read — well done. I'm working with PrimeRx, a pharmacy management software platform, and we have some content around pharmacy automation, inventory optimization, and patient engagement tech that could be a fit for your readers.\n\nWould you be open to a contributed article? We handle all the drafting.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, floating this back to the top. Happy to share a few topic ideas so you can see if anything clicks.\n\nYam`,`Hi {{FIRSTNAME}}, wanted to follow up once more. We can write to your editorial standards and are glad to cover any editorial fees. Let me know.\n\nYam`,`Last note from me on this — no worries if it's not the right time. Open invitation stands if you need healthcare/pharmacy tech content in the future.\n\nYam`] },
  'SMOKEA': { subjects: ['Content idea for {{SITE_NAME}}','Re: Content idea for {{SITE_NAME}}','Re: Content idea for {{SITE_NAME}}','Re: Content idea for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nCame across your piece on {{ARTICLE_TITLE}} — good stuff. I work with SMOKEA (online smoke shop) and we have some content ready around topics like choosing the right glass, smoking accessory guides, and what's trending in the smoke shop space.\n\nInterested in a contributed article? We write everything — you just publish.\n\nCheers,\nYam`,`Hey {{FIRSTNAME}}, just following up on my last email. Happy to fire over topic ideas if that's easier.\n\nYam`,`Hi {{FIRSTNAME}}, checking in here. We're flexible on topics and glad to cover any editorial fees on your end. Would love to collaborate.\n\nYam`,`Last reach-out from me. If you're ever open to contributed content, feel free to hit me up.\n\nYam`] },
  'MRSKIN': { subjects: ['Collab idea — {{SITE_NAME}}','Re: Collab idea — {{SITE_NAME}}','Re: Collab idea — {{SITE_NAME}}','Re: Collab idea — {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nYour {{ARTICLE_TITLE}} was a fun read — exactly my kind of content. I'm working with MrSkin (the go-to database for movie and TV scenes) and we have some article ideas around iconic movie moments, best scenes by genre, and celebrity filmography deep-dives.\n\nWould you be up for a contributed piece? We handle the writing.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just bumping this. Can send over a few specific topic ideas if that helps you decide.\n\nYam`,`Hi {{FIRSTNAME}}, following up one more time. We can match your tone and style, and we're happy to cover any editorial or publishing fees. Let me know if there's room.\n\nYam`,`Last one from me — if entertainment content collabs make sense later, the offer stands.\n\nYam`] },
  'VRAI': { subjects: ['Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nReally enjoyed your piece on {{ARTICLE_TITLE}} — great perspective. I'm working with VRAI, a lab-grown diamond jewelry brand, and we have article ideas around lab-grown diamond education, sustainable luxury, and engagement ring trends that I think your audience would appreciate.\n\nWould you be open to a contributed article? We handle the writing.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just circling back. Happy to share a few polished topic options for your review.\n\nYam`,`Hi {{FIRSTNAME}}, following up here. We write to your editorial guidelines and are happy to cover any editorial fees. Would love to collaborate.\n\nYam`,`Last message from me — if sustainability or jewelry content is ever needed, we're here.\n\nYam`] },
  'AMS-FULFILLMENT': { subjects: ['Guest contribution for {{SITE_NAME}}?','Re: Guest contribution for {{SITE_NAME}}?','Re: Guest contribution for {{SITE_NAME}}?','Re: Guest contribution for {{SITE_NAME}}?'], bodies: [`Hi {{FIRSTNAME}},\n\nFound your article on {{ARTICLE_TITLE}} while researching fulfillment content — well put together. I work with AMS Fulfillment (3PL provider) and we have articles on topics like scaling fulfillment operations, choosing a 3PL partner, and reducing shipping costs that would fit your audience.\n\nOpen to a contributed piece? We do all the writing.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just following up. Can share topic ideas if that makes it easier to evaluate.\n\nYam`,`Hi {{FIRSTNAME}}, circling back once more. We write to your standards and are happy to cover any editorial costs. Let me know if there's interest.\n\nYam`,`Closing the loop here. If ecommerce/logistics content makes sense in the future, happy to reconnect.\n\nYam`] },
  'BUILT-BAR': { subjects: ['Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}','Re: Article idea for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nYour post on {{ARTICLE_TITLE}} was great — practical and well-researched. I'm working with Built Bar (protein bar brand) and we have content around on-the-go nutrition, protein bar comparisons, and healthy snacking for active lifestyles that would resonate with your readers.\n\nInterested in a contributed article? We handle the writing.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just bumping this. Happy to send topic ideas your way — no commitment needed upfront.\n\nYam`,`Hi {{FIRSTNAME}}, one more follow-up. We can tailor content to your style and are glad to cover any editorial fees. Let me know.\n\nYam`,`Last note from me — if fitness or nutrition content is something you're looking for later, feel free to reach out.\n\nYam`] },
  'NUTRABIO': { subjects: ['Contribution idea — {{SITE_NAME}}','Re: Contribution idea — {{SITE_NAME}}','Re: Contribution idea — {{SITE_NAME}}','Re: Contribution idea — {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nBeen reading your content — your piece on {{ARTICLE_TITLE}} stood out. I work with NutraBio (sports nutrition brand known for full-label transparency) and we have articles on topics like supplement transparency, pre-workout science, and protein quality that would be a strong fit for your site.\n\nWould you be up for a contributed article? We handle the writing end.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, floating this back up. Can send over specific topic options if that helps.\n\nYam`,`Hi {{FIRSTNAME}}, following up once more. We write to your specs and are happy to cover any editorial fees on your end. Would love to make it work.\n\nYam`,`Closing the loop — if supplement or fitness content is ever needed, we're here. No pressure.\n\nYam`] },
  'VIVANTE-LIVING': { subjects: ['Content idea for {{SITE_NAME}}','Re: Content idea for {{SITE_NAME}}','Re: Content idea for {{SITE_NAME}}','Re: Content idea for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nYour piece on {{ARTICLE_TITLE}} caught my eye — beautiful editorial approach. I'm working with Vivante Living (luxury home goods and furniture brand) and we have content around interior styling trends, choosing statement furniture, and curating a luxury living space that would complement your site well.\n\nWould you be open to a contributed article? We handle the writing.\n\nBest,\nYam`,`Hey {{FIRSTNAME}}, just circling back. Happy to share a few refined topic ideas for your consideration.\n\nYam`,`Hi {{FIRSTNAME}}, following up once more. We write to your style and are glad to cover any editorial fees involved. Let me know if there's a fit.\n\nYam`,`Last reach-out from me. If home decor or luxury living content is ever on your radar, the offer's open.\n\nYam`] },
  'GOODR': { subjects: ['Quick idea for {{SITE_NAME}}','Re: Quick idea for {{SITE_NAME}}','Re: Quick idea for {{SITE_NAME}}','Re: Quick idea for {{SITE_NAME}}'], bodies: [`Hi {{FIRSTNAME}},\n\nLoved your post on {{ARTICLE_TITLE}} — right up my alley. I work with Goodr (the fun sunglasses brand built for runners and athletes) and we've got content ideas around running gear essentials, finding the right sports sunglasses, and staying stylish on the trail that would work great on your site.\n\nInterested in a contributed article? We take care of all the writing.\n\nCheers,\nYam`,`Hey {{FIRSTNAME}}, just bumping this. Happy to send a few specific topics your way — no strings attached.\n\nYam`,`Hi {{FIRSTNAME}}, following up one more time. We can match your voice and style, and are happy to cover any editorial fees. Would love to collaborate.\n\nYam`,`Last one from me — if running or outdoor gear content makes sense down the road, I'm a message away.\n\nYam`] },
};

/**
 * Fill template placeholders with contact data
 */
function fillTemplate(text, contact) {
  return text
    .replace(/\{\{FIRSTNAME\}\}/g, contact.firstName || 'there')
    .replace(/\{\{SITE_NAME\}\}/g, contact.siteName || contact.domain || '')
    .replace(/\{\{ARTICLE_TITLE\}\}/g, contact.articleTitle || 'your recent content')
    .replace(/\{\{DOMAIN\}\}/g, contact.domain || '');
}

/**
 * Build HTML email body from plain text template
 */
function toHtml(text) {
  const escaped = text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return `<html><body><p style="font-family:Arial,sans-serif;font-size:14px;line-height:1.5">${escaped.replace(/\n/g, '<br>')}</p></body></html>`;
}

module.exports = { TEMPLATES, fillTemplate, toHtml };
